name: Terraform validation

on:
  pull_request:
    branches:
    - main
    paths:
    - '**.tf'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create zip
      run: Make qualys_rss.zip
    - name: terraform init
      run: terraform init
    - name: terraform validate
      run: terraform validate
    - name: terraform fmt
      run: terraform fmt -check -recursive
