name: Zip Validation

on:
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'qualys_rss.zip'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: unzip
      run: make validate_zip
